name: iot
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=51_gnu
  - blas=1.0=openblas
  - bzip2=1.0.8=h998d150_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cffi=1.15.0=py310h8915cd8_0
  - expat=2.7.1=h419075a_0
  - gettext=0.19.8.1=h6edf1e2_1008
  - ld_impl_linux-aarch64=2.44=h4e4ac68_2
  - libffi=3.4.4=h419075a_1
  - libflac=1.3.4=h4de3ea5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h6e398d7_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libogg=1.3.4=h3557bc0_1
  - libopenblas=0.3.30=h90745d9_0
  - libopus=1.3.1=hf897c2e_1
  - libsndfile=1.0.31=h01db608_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h998d150_0
  - libvorbis=1.3.7=h01db608_0
  - libxcb=1.17.0=hf66535e_0
  - libzlib=1.3.1=h998d150_0
  - ncurses=6.5=h419075a_0
  - numpy=2.0.1=py310he45c16d_1
  - numpy-base=2.0.1=py310h15d264d_1
  - openssl=3.0.18=h8a9c3cf_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=hfd63f10_1
  - pycparser=2.22=pyh29332c3_1
  - pysoundfile=0.11.0=pyhd8ed1ab_0
  - python=3.10.18=hbb0f47a_0
  - python-dotenv=1.1.1=pyhe01879c_0
  - python_abi=3.10=2_cp310
  - readline=8.3=h886d1d0_0
  - setuptools=80.9.0=py310hd43f75c_0
  - sqlite=3.50.2=h998d150_1
  - tk=8.6.15=h987d8db_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310hd43f75c_0
  - xorg-libx11=1.8.12=hf66535e_1
  - xorg-libxau=1.0.12=hf66535e_0
  - xorg-libxdmcp=1.1.5=hf66535e_0
  - xorg-xorgproto=2024.1=h998d150_1
  - xz=5.6.4=h998d150_1
  - zlib=1.3.1=h998d150_0
  - pip:
      - adafruit-blinka==8.66.2
      - adafruit-circuitpython-busdevice==5.2.13
      - adafruit-circuitpython-connectionmanager==3.1.5
      - adafruit-circuitpython-requests==4.1.13
      - adafruit-circuitpython-typing==1.12.2
      - adafruit-circuitpython-vl53l1x==1.2.5
      - adafruit-platformdetect==3.84.0
      - adafruit-pureio==1.1.11
      - binho-host-adapter==0.1.6
      - board==1.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.3
      - future==1.0.0
      - idna==3.11
      - iso8601==2.1.0
      - jetson-gpio==2.1.12
      - opencv-python==4.12.0.88
      - paho-mqtt==2.1.0
      - pydub==0.25.1
      - pyftdi==0.57.1
      - pynmea2==1.19.0
      - pyserial==3.5
      - pyusb==1.3.1
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - requests==2.32.5
      - scipy==1.15.3
      - serial==0.0.97
      - sounddevice==0.5.2
      - sysv-ipc==1.1.0
      - toml==0.10.2
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - zmq==0.0.0
prefix: /home/jetson/miniconda3/envs/iot
